### ISSUE TITLE
Add /marvin delegate @[...]

### ISSUE THREAD

**Issue by blaggacao** [timokau/marvin-mk2#47]
https://github.com/NixOS/nixpkgs/pull/92243#issuecomment-653746032

(Aside: marvin could apply those same heuristics exposed in the comment on git logs to assign in the first place.)

Enables reliable identification of #44 

I would argue a best-effort manual delegation _by the delegating reviewer_ (which is marvin enabled, thus trustworthy) could be opt-out for the targeted reviewer. That implied those reviewers need not necesarily be in marvin's internal maintainer list.

**Comment by timokau** [comment]
Marvin doesn't need to know who is currently "responsible", it only needs to know that *someone* is. It might be nice to know *who* is, but that requires more explicit commands. The goal is to get out of everyone's way as much as possible and make a normal PR workflow possible.

The problem in https://github.com/NixOS/nixpkgs/pull/92243#issuecomment-653746032 has been resolved by #58.

> Aside: marvin could apply those same heuristics exposed in the comment on git logs to assign in the first place.

That's not possible / desirable because of two reasons:
- most people will not have signed up as a marvin reviewer / will not be available. I want people to actually respond to review requests, and that works best when they actively signed up for it. Repeatedly "nagging" the same few "domain experts" will just lead to them ignoring the requests
- it further centralizes knowledge. If a random "shepherd" is selected instead, they can use their own judgement to delegate review and they will also learn from the feedback of the new reviewer.

**Comment by blaggacao** [comment]
Very true arguments. Closing this as errata.
