### ISSUE TITLE
RFC-30 / RFC-0036 / RFC-0039 / RFC-0051 / RFC-0055

### ISSUE THREAD

**Issue by blaggacao** [timokau/marvin-mk2#66]
Marvin is basically a trial run of rfc 30. ([comment](https://github.com/timokau/marvin-mk2/issues/66#issuecomment-656231243))
- https://github.com/NixOS/rfcs/pull/30/

See also: 
- https://github.com/NixOS/rfcs/blob/master/rfcs/0036-review-process.png
- https://github.com/NixOS/rfcs/blob/master/rfcs/0039-unprivileged-maintainer-teams.md
- https://github.com/NixOS/rfcs/blob/master/rfcs/0051-mark-stale-issues.md
- https://github.com/NixOS/rfcs/blob/master/rfcs/0055-retired-committers.md

**Comment by timokau** [comment]
Marvin is basically a trial run of [rfc 30](https://github.com/NixOS/rfcs/pull/30). What is the intention of this issue? Is there something actionable?

The maintainer teams in 39 help for requesting reviews, but not everyone is in those teams. Stalebot might eventually be replaced, but thats way off into the future. The two can happily co-exist, there is just little point to stalebot with marvin. 55 seems unrelated.

**Comment by blaggacao** [comment]
> What is the intention of this issue?

Help materializing the mental map of third party by-sailors (and myself) out of somewhat fragmented information.

> Is there something actionable?

Not directly.

> 55 seems unrelated.

I put it since marvin might _eventually_ choose to adopt general maintainers listings as it graduates, in that case it can also reflect the [emeritus](https://github.com/NixOS/rfcs/pull/71) status.

**Comment by timokau** [comment]
> final version of marvin might actually update RFC-0036

36 is about the RFC process, unrelated to PR reviews.

> I put it since marvin might eventually choose to adopt general maintainers listings as it graduates, in that case it could also reflect the emeritus / retired status.

I don't think it will ever pull reviewers from the maintainers list, if that is what you mean. As mentioned previously, I'd rather have people review who actively signed up for it (and set a rate limit). ofBorg already pings maintainers.

Also even if we were to do that, we wouldn't have to take any action regarding 55 since we could just pull from the team.

> Help materializing the mental map of third party by-sailors (and myself) out of somewhat fragmented information.

It might be a good idea to mention RFC 30, maybe also 51 in the README. Feel free to open a PR if you like. I'll close the issue for now, since this is probably not the best place to make the RFCs discoverable. I'd rather keep the issue tracker actionable.

**Comment by blaggacao** [comment]
Nice and actionable suggestion. Thanks for clarification, this might help others as well to wrap their head around.
